name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: conditional
        if:  ${{ inputs.config-path  != ''}}
        run: |
          echo "QUE NO TE PUEO CREER ${{ inputs.config-path}}"
